version: '2'
services:
  web:
    restart: always
    image: acmecorp/acme
    ports:
      - "5000:5000"
    tty: true
    environment:
      FLASK_APP: app.py
    command: python -m flask run --host=0.0.0.0
